version: '3.1'
services:
  db-{{cookiecutter.code_name}}:
    image: postgres:11-alpine
    restart: unless-stopped
    container_name: db-{{cookiecutter.code_name}}
    env_file:
     - ./docker.env
    ports:
     - "5432:5432"
    networks:
      - {{cookiecutter.company}}_apps
  {{cookiecutter.code_name}}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    command: ./entrypoint.sh
    image: {{cookiecutter.company}}-{{cookiecutter.code_name}}
    container_name: {{cookiecutter.code_name}}
    env_file:
     - ./docker.env
    links:
      - db-{{cookiecutter.code_name}}
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - {{cookiecutter.company}}_apps

networks:
  {{cookiecutter.company}}_apps:
    external: true
