version: '3.1'
services:
  {{cookiecutter.code_name}}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    command: ./entrypoint.sh
    image: {{cookiecutter.company}}-{{cookiecutter.code_name}}
    container_name: {{cookiecutter.code_name}}
    env_file:
     - ./docker.sqlite.env
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - {{cookiecutter.company}}_apps

networks:
  {{cookiecutter.company}}_apps:
    external: true
