version: '3.1'
services:
  db-purohueso:
    image: postgres:11-alpine
    restart: unless-stopped
    container_name: db-purohueso
    env_file:
     - ./docker.env
    ports:
     - "5432:5432"
    networks:
      - lvm_apps
  purohueso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    command: ./entrypoint.sh
    image: lvm-purohueso
    container_name: purohueso
    env_file:
     - ./docker.env
    links:
      - db-purohueso
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - lvm_apps

networks:
  lvm_apps:
    external: true
